# "org" ensures this Service is used with the correct Serverless Framework Access Key.
service: nextjs-app

frameworkVersion: '4.4.10'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  api:
    handler: handler.main
    events:
      - http:
          path: /api/stores
          method: post
          cors: true